/// Seed corpora for the Markov namer.
///
/// Invented-sounding but phonotactically plausible stems. They are training
/// material, not output: the namer rejects any candidate that matches a corpus
/// entry verbatim, so nothing here reaches the league unaltered.
library;

/// Town and city stems, used for club home towns.
const List<String> townCorpus = <String>[
  'ashcombe',
  'barrowfield',
  'blackmoor',
  'bridgeholt',
  'carrowmere',
  'castlerea',
  'cindermoor',
  'dunwich',
  'eastmarch',
  'elderbrook',
  'fenwick',
  'gallowsend',
  'glenmorne',
  'greyfell',
  'harrowgate',
  'hollowmere',
  'kestrelby',
  'kilnaugh',
  'lambrook',
  'longbarrow',
  'marlowe',
  'millthorpe',
  'northwold',
  'oakhaven',
  'orrinshaw',
  'pellingham',
  'quarrymouth',
  'ravensworth',
  'redmarley',
  'rookhurst',
  'saltcombe',
  'shawbury',
  'stonebridge',
  'tarnwick',
  'thornbury',
  'underhill',
  'vale',
  'westerling',
  'whitmarsh',
  'wyndham',
];

/// Club suffixes, giving the league its own idiom.
const List<String> clubSuffixes = <String>[
  'Athletic',
  'City',
  'Rangers',
  'Rovers',
  'Town',
  'United',
  'Wanderers',
  'Albion',
  'Corinthians',
  'Foundry',
  'Mariners',
  'Colliery',
];

/// Surname stems for players.
const List<String> surnameCorpus = <String>[
  'ashford',
  'birtwistle',
  'braddock',
  'calloway',
  'carrick',
  'crowther',
  'darnley',
  'eastwood',
  'fairbrother',
  'garrow',
  'halloran',
  'hexham',
  'ingleby',
  'kirkwood',
  'lansbury',
  'lockhart',
  'mallory',
  'merrick',
  'norwood',
  'oakley',
  'pemberton',
  'quillan',
  'radcliffe',
  'rutherford',
  'selby',
  'shackleton',
  'thackeray',
  'trenholme',
  'underwood',
  'vance',
  'wainwright',
  'whitlock',
  'yarrow',
];

/// Forename stems for players.
const List<String> forenameCorpus = <String>[
  'alaric',
  'bertram',
  'callum',
  'davey',
  'edwin',
  'fergus',
  'gareth',
  'hollis',
  'ivor',
  'jonty',
  'kester',
  'lachlan',
  'merrick',
  'niall',
  'osric',
  'perrin',
  'quentin',
  'roland',
  'silas',
  'tobias',
  'ulric',
  'vaughn',
  'wilfred',
  'yorick',
];
